server:
  port: 8888
spring:
#  profiles:
#    active: dev
  application:
    name: elasticSearchDemo
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
#      cluster-name: my-es
      repositories:
        enabled: true